import { Controller, Get, Param, Res } from '@nestjs/common';
import { Response } from 'express';
import { AnalyticsService } from './analytics.service';

@Controller('analytics')
export class AnalyticsController {
    constructor(private readonly analytics: AnalyticsService) { }

    @Get('summary')
    getSummary() {
        return this.analytics.getSummary();
    }

    @Get('postmortem/:id')
    async getPostmortem(@Param('id') id: string, @Res() res: Response) {
        const data = await this.analytics.getPostmortem(id);
        if (!data) return res.status(404).json({ error: 'Not found' });

        const md = `# CHIMERA Incident Postmortem

**ID:** ${data.id}
**Title:** ${data.title}
**Severity:** ${data.severity}
**Service:** ${data.service}
**Created:** ${new Date(data.created_at).toISOString()}
**Resolved:** ${new Date(data.resolved_at).toISOString()}

---

## Summary

| Metric | Value |
|--------|-------|
| Incident Class | \`${data.incident_class}\` |
| Resolution Time | ${(data.resolution_ms / 1000).toFixed(1)}s |
| Agent Confidence | ${(data.confidence * 100).toFixed(0)}% |
| Agents Deployed | ${data.agents_used} |
| Memory Recall | ${data.from_memory ? '⚡ Yes (instant recall)' : 'No (synthesized)'} |
| Adversarial Dissents | ${data.dissents} |

---

## Resolution Decision

${data.decision}

---

## Timeline

- **${new Date(data.created_at).toLocaleTimeString()}** — Incident received by CHIMERA
- **+${data.from_memory ? '~2' : '~21'}s** — Agent topology ${data.from_memory ? 'recalled from memory' : 'synthesized by Qwen'}
- **+${(data.resolution_ms / 1000 * 0.7).toFixed(0)}s** — Specialist agents completed investigation
- **+${(data.resolution_ms / 1000 * 0.9).toFixed(0)}s** — Adversarial validation completed
- **+${(data.resolution_ms / 1000).toFixed(1)}s** — Consensus reached, incident resolved

---

*Generated by CHIMERA · Autonomous Incident Response · Powered by Qwen Cloud on Alibaba Cloud*
`;

        res.setHeader('Content-Type', 'text/markdown');
        res.setHeader('Content-Disposition', `attachment; filename="postmortem-${id.slice(0, 8)}.md"`);
        return res.send(md);
    }
}